### ISSUE TITLE
PBR conductor_bsdf has default input values outside valid color range

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1190]
Some of the input values for `conductor_bsdf` are specified as `color`s but have values outside the 0..1 "valid" range.
Leaving a query here if this is correct and whether these should instead be of type `vector` ? Unsure if there are any issues with `colorspace` as this is a explicitly specified attribute. They won't translate well to UI which assumes 0..1 range like a color picker.
```
<!--
    Node: <conductor_bsdf>
    A reflection BSDF node based on a microfacet model and a Fresnel curve for conductors/metals.
  -->
  <nodedef name="ND_conductor_bsdf" node="conductor_bsdf" bsdf="R" nodegroup="pbr" doc="A reflection BSDF node based on a microfacet model and a Fresnel curve for conductors/metals.">
    <input name="weight" type="float" value="1.0" uimin="0.0" uimax="1.0" />
    <input name="ior" type="color3" value="0.271, 0.677, 1.316" colorspace="none" />
    <input name="extinction" type="color3" value="3.609, 2.625, 2.292" colorspace="none" />
    <input name="roughness" type="vector2" value="0.05, 0.05" />
    <input name="normal" type="vector3" defaultgeomprop="Nworld" />
    <input name="tangent" type="vector3" defaultgeomprop="Tworld" />
    <input name="distribution" type="string" value="ggx" enum="ggx" uniform="true" />
    <output name="out" type="BSDF" />
  </nodedef>
 ```

**Comment by jstone-lucasfilm** [comment]
@kwokcb This is an interesting topic for discussion, and the two color inputs to this BSDF node are "non-perceptual" colors, as described in this SIGGRAPH 2020 talk by Naty Hoffman:

https://blog.selfshadow.com/publications/s2020-shading-course/hoffman/s2020_pbs_hoffman_slides.pdf#page=42

In MaterialX, we have historically expressed non-perceptual colors as values of type "color3" with their colorspace set to "none", so that they are not affected by colorspace transforms.

It's important to note that values of type "color3" are not limited to the [0-1] range, even though color picking interfaces often make it difficult to select values outside of this range.  Even for fully perceptual colors such as reflectance, it's allowable for channels to take on values greater than one, or even to take on negative values when expressing colors outside of the gamut in which they are represented.

**Comment by kwokcb** [comment]
Perhaps it's worthwhile consider allowing a "hint" to specify something as a "non-perceptual" color ? 
Then folks would, for instance, not try and convert the value to a 8-bit RGB color or a hex value, or add a colorspace transform.
(I ran into issues when trying to get a hex value).

**Comment by jstone-lucasfilm** [comment]
That's an interesting suggestion, though I should note that _all_ colors are allowed to exceed the [0-1] range, not just non-perceptual colors like `ior` and `extinction`.  In production, for example, it's relatively common to encounter color triples and textures with negative values, when a color originally stored in `acescg` has been transformed to `lin_rec709` and it no longer fits within the new, smaller gamut of that colorspace.

For non-perceptual colors like `ior` and `extinction`, their really unique quality is that they cannot meaningfully be transformed between color spaces.  To denote that unique quality, perhaps it's sufficient that we set their `colorspace` attribute to `none`?

**Comment by kwokcb** [comment]
The `colorspace` tag seems reasonable but the spec current says "The default is "none", for no color management", so maybe "splitting hairs" here but perhaps a different keyword than "none".

**Comment by jstone-lucasfilm** [comment]
These are good points, and I believe we should improve our handling of physical/non-perceptual colors in the future, though I'd want to consult with Naty and other domain experts before proposing a new approach.  Since the current issue is focused on colors outside of the [0-1] range, and these are allowed in MaterialX, I'll close this out and we can consider non-perceptual colors to be a future discussion topic.
