### ISSUE TITLE
Material node not found if used in material definition

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1198]
If a `material` node is used inside a `nodedef` then it is not discovered by 
```c++
Document::getMaterialNodes()
```
* The node is found to be a `material` but since it has inputs the search to find shader nodes within the definition is skipped
erroneously.
* Note that this is used by the "find renderable elements" utility so these nodes are currently always miscategorized as not being materials.
* The easy fix is to skip only if no shader nodes are found already as that is the test for a "valid" material node.
Example definition, such that the check for inputs returns true, so the nodedef graph is not scanned.
```xml
  <nodedef name="ND_convert_color3_material_1_0" node="convert" version="1.0" isdefaultversion="true" nodegroup="material" doc="Convert color3 to material">
    <input name="in" type="color3" value="1, 1, 1" />
    <output name="out" type="material" />
  </nodedef>
  <nodegraph name="NG_convert_color3_material_1_0" nodedef="ND_convert_color3_material_1_0">
    <surface_unlit name="surface_unlit" type="surfaceshader" >
      <input name="emission_color" type="color3" interfacename="in" />
    </surface_unlit>
    <surfacematerial name="surfacematerial" type="material" >
      <input name="surfaceshader" type="surfaceshader" nodename="surface_unlit" />
      <input name="displacementshader" type="displacementshader" value="" />
    </surfacematerial>
    <output name="out" type="material" nodename="surfacematerial" />
  </nodegraph>
```
`

**Comment by jstone-lucasfilm** [comment]
@kwokcb I believe this is by design, and `GraphElement::getMaterialNodes` is only intended to return material nodes that are owned by a single GraphElement, though we could definitely improve our documentation on this:

https://materialx.org/docs/api/class_graph_element.html#a8d1b55f2dfcfce37410b56e92758a099

**Comment by jstone-lucasfilm** [comment]
I'll close out this issue, since the current behavior appears to be correct, but improvements to our documentation are always appreciated!

**Comment by kwokcb** [comment]
Hi @jstone-lucasfilm,
This doesn't change the logic of ownership I don't think.

Basically this method has a sanity check to see if there are any shader nodes used. It current works if the shader node is an input, but not if it's an internal node on the functional graph (as is the case above).

The patch fix is to check if there are any shader nodes in the functional graph not found as an input. The current logic
(which is incorrect) is never check the functional graph if there are no shader inputs.
The one line patch is here:

https://github.com/kwokcb/MaterialX/pull/36/files#diff-254fbf49c66e810d9d82bb0cc41563bcf101768b47e0e4ab6814f01c00d62073L75

**Comment by jstone-lucasfilm** [comment]
@kwokcb Ah, I wasn't clear on what you were reporting as the issue here.  I'd thought that you were reporting that Document::getMaterialNodes doesn't return material nodes that are inside of a NodeDef, and that is indeed by design.  Perhaps the most straightforward approach would be to post this single fix in a new pull request, and we can analyze it there?
