### ISSUE TITLE
ninja error while enabled building Viewer and Node Graph Editor 

### ISSUE THREAD

**Issue by igor-elovikov** [AcademySoftwareFoundation/MaterialX#1208]
With default settings if I set to build both I'm experiencing this error:
`ninja: error: build.ninja:3662: multiple rules generate lib/glfw3.lib [-w dupbuild=err]` I guess there is some conflict with imgui and NanoGUI backends

I've managed to built both apps using `-DMATERIALX_BUILD_SHARED_LIBS:BOOL=ON` though this one isn't default.

* Cmake 3.24.2 Windows 11

**Comment by dgovil** [comment]
Hitting the same here. I'd switched to the Make backend which worked, but yeah your suggestion works around the issue for Ninja

**Comment by jstone-lucasfilm** [comment]
Good catch, @igor-elovikov, and this similar to an issue that we encountered in CMake/Make builds, since NanoGUI includes its own local copy of the `glfw` library.

To resolve the CMake/Make issue, we made small modifications to the copy of `glfw` used in the Graph Editor, so that its project name wouldn't overlap the one in NanoGUI.

Could it be that a similar renaming of library outputs might resolve the issue in CMake/Ninja builds?

**Comment by dgovil** [comment]
I think either renaming the target, or sharing the target should work. ie only configuring the GLFW target for the graph editor if the one for NanoGUI isn't setup already (and vice versa, though I think you can guarantee the GraphEditor comes after the Viewer)

**Comment by igor-elovikov** [comment]
I've made a small PR that I'm using to build graph and viewer at the same time
essentially just renamed lib name for graph editor

**Comment by jstone-lucasfilm** [comment]
Thanks to @igor-elovikov for the fix!
