### ISSUE TITLE
Issues overriding OSL shader nodes implementations.

### ISSUE THREAD

**Issue by dcourtois** [AcademySoftwareFoundation/MaterialX#1409]
Hi,
I wanted to override the OSL implementation of the `UsdPrimvarReader` nodes. I'm using a custom target which inherits from `genosl`, and a custom shader generator class which inherits from `OslShaderGenerator`.
In its constructor, I'm registering implementations for the nodes I want to override, like so:
```
    registerImplementation({
            "IMP_UsdPrimvarReader_integer_" + getTarget(),
            "IMP_UsdPrimvarReader_boolean_" + getTarget(),,
            "IMP_UsdPrimvarReader_string_" + getTarget(),,
            "IMP_UsdPrimvarReader_float_" + getTarget(),,
            "IMP_UsdPrimvarReader_vector2_" + getTarget(),,
            "IMP_UsdPrimvarReader_vector3_" + getTarget(),,
            "IMP_UsdPrimvarReader_vector4_" + getTarget(),
        }, [] (void) -> mx::ShaderNodeImplPtr {
            return std::make_shared<CustomPrimvarReaderNode>();
        }
    );
```

But I never enter the "creator" callback.

To debug this, I overloaded the `getImplementation` method of my shader generator, and I checked how the `nodedef.getImplementation(getTarget());` call was behaving for my custom nodes.

Turns out the issue is here: https://github.com/AcademySoftwareFoundation/MaterialX/blob/2c50d91cfa3ac61546b4118bd4e216169373382b/source/MaterialXCore/Definition.cpp#L75-L85

In this loop, `candidateTargets` is equal to `[ "MyTarget", "genosl" ]` as expected, and `interfaces` contains 2 implementations: the first one from OSL, and the second one is the one I registered for my target, *in this order* (this is important)
And the problem is that the `targetStringsMatch` will return true if either of its parameter is an empty string. Which is the case for `interface->getTarget()`... And thus the function returns the first interface, e.g. the one from OSL, instead of mine.

I'm not sure what's the real problem here: should the target be set to `genosl` for all OSL implementations (it feels like it should?) or is it that `targetStringsMatch` returns true if either of its argument is empty? In any case, it feels a bit weird that this `getImplementation` stops on the first things that matches, instead of trying to first look up for a perfect match (e.g. both targets are the exact same) and then fallback to trying to match by inheritance / whatever.

I'm going to try to remove the OSL implementations before registering my own, but I thought this behavior was a bit buggy so I opened this issue to get more info (it might also be something I'm doing wrong :p).

Edit: Hmm, I thought it would be quite easy to remove the default implementations of those nodes, but it turns out it's a bit of a nightmare, so if anyone has a suggestion to workaround this, I'm all ears/eyes :p

**Comment by kwokcb** [comment]
Hi @dcourtois,

I think the issue is that the implementations checked are not based on candidate target order. If they were then
the first candidates implementations would be checked first (`MyTarget`) then the inherited ones (`genosl`), then those that have no target would be checked last (empty target).

I think `targetStringsMatch` should be updated to only test if the first target (and not the second) is empty as would mean it that it is generic enough to match all targets.

We do have inheritance where the derived implementations should be used, but it could be that there is no example of a code implementation override for a nodegraph implementation (which has no target = empty string).

----

It does feel like this logic path should not even be followed if the implementations are registered with the code generator already. I'll leave a ping with @niklasharrysson for any comment.

**Comment by kwokcb** [comment]
Hi @dcourtois,
Good to hear that your not blocked but indeed a general fix should be made. Thanks for the code reference.

**Comment by kwokcb** [comment]
@dcourtois, In case you didn't see the PR ping. I've put up something for you to try out.

**Comment by dcourtois** [comment]
Currently OOO, I’ll have a look at it tomorrow, thanks a lot!
