### ISSUE TITLE
Aliasing artifacts in tiled hexagon pattern

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1490]
It seems that if you set enough repeats and zoom out a bit that the hex pattern will appear distorted.

Here is an example file test on a plane geometry:
```xml
<?xml version="1.0"?>
<materialx version="1.38" colorspace="lin_rec709">
  <surface_unlit name="surface_unlit" type="surfaceshader" xpos="14.579710" ypos="-3.224138">
    <input name="emission_color" type="color3" output="output_color3" nodegraph="nodegraph1" />
  </surface_unlit>
  <nodegraph name="nodegraph1">
    <output name="output_color3" type="color3" nodename="tiledhexagons_color3" xpos="16.355072" ypos="-2.594828" />
    <tiledhexagons name="tiledhexagons_color3" type="color3" xpos="12.956522" ypos="-3.189655">
      <input name="size" type="float" interfacename="size" />
      <input name="uvtiling" type="vector2" interfacename="tiling" />
      <input name="staggered" type="boolean" value="false" />
    </tiledhexagons>
    <input name="size" type="float" value="0.6" xpos="10.652174" ypos="-4.250000" />
    <input name="tiling" type="vector2" value="17.1, 16.1" xpos="10.673913" ypos="-2.870690" />
  </nodegraph>
</materialx>
```
![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/49369885/0196a2b6-fa7e-42af-8b00-8153975058f5)

Not sure but could it be a tolerance needs to be added to the `<ifgreater>` and `<ifequal>` tests.

**Comment by jstone-lucasfilm** [comment]
@kwokcb This is a good note, and I suspect what you're seeing here is _aliasing_, caused by a high-frequency hexagon pattern being evaluated only once per pixel of the rendered image.

So far, my thinking has been that we'll resolve this generically by writing anti-aliased implementations of the MaterialX _primitives_ in the future, allowing users to opt into this feature at shader compilation time.

I'm very interested in additional thoughts from the community on this, though, and this would make a good topic for a future MaterialX TSC meeting.

**Comment by kwokcb** [comment]
I guess any pattern can suffer from aliasing, but I don't noticed this for instance with "noise" procedurals for instance (with in object positions). No matter how much I zoom the pattern seems "stable". Not sure if this is a "apples" with "apples" comparison.

**Comment by jstone-lucasfilm** [comment]
@kwokcb I would expect these artifacts to be most noticeable with MaterialX nodes that behave like "step" functions, where a binary choice is made between two inputs based on a comparison.  This type of binary choice occurs at the boundaries of shapes in the new line, circle, and hexagon nodes, but it's not really present in smooth functions like Perlin noise.

To my current thinking, we'd want to address this in the implementations of MaterialX nodes that behave like step functions (e.g. `ifgreater`), by providing antialiased versions that users can enable at shader generation time, though I'm very open to other ideas from the community.

There's some good background on this subject here, and it's a topic that I know the authors of RSL and OSL have given a lot of thought to:

https://renderman.pixar.com/resources/RenderMan_20/basicAntialiasing.html

**Comment by jstone-lucasfilm** [comment]
We had a chance to discuss this in depth at our last MaterialX TSC and on the ASWF Slack, and one key takeaway is that each renderer will need to handle antialiasing in its own appropriate fashion, rather than MaterialX providing an automated antialiasing solution.

Let's plan continue this discussion on the ASWF Slack, where a good summary thread can be found [here](https://academysoftwarefdn.slack.com/archives/C0230LWBE2X/p1693334463056569).
