### ISSUE TITLE
New Python workflow seems to cause all sorts of "random" CI errors w/ extra module?

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1497]
I'm not sure what's going on since it's really hard to read the Python build workflows  but after syncing the new CI changes, I'm getting all kinds of random failures. Some seem to run some don't for different reasons.

I have an extra module in the fork / branch this is running from:
https://github.com/KhronosGroup/MaterialX/actions/runs/5982377024

Any help to figure out what's going would help.

**Comment by jstone-lucasfilm** [comment]
@kwokcb I haven't seen these errors in other forks of MaterialX, so it does sound like an issue that's triggered by specific differences in the Khronos fork.

Taking a step back, though, I wonder if it would be better to restrict the new `python` workflow to the ASWF repository of MaterialX, rather than running it in all forks of the MaterialX project.

**Comment by jstone-lucasfilm** [comment]
In PR #1511, I've restricted Python Wheel generation to the ASWF MaterialX repository, so that this work doesn't also run in MaterialX forks.

I'll close out this issue for now, and going forward I believe it would be valuable to improve our documentation for the requirements of custom MaterialX modules with Python bindings.
