### ISSUE TITLE
CodeGen: Update codegen optimization code to handle `ifgreatereq`

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1527]
## Issue:

`compare` was removed in 1.37 but not updated in code optimization for `igreatereq` which was added.

## Proposal

Consider adding this optimization back in to test if the upstream decision argument is a constant. If so then  add back in code optimization. 

It might be worthwhile to consider making optimizations based on conditionals to be a code generation option. This way if an integration wants to not have to regenerate on conditional changes they can.

**Comment by jstone-lucasfilm** [comment]
As with #1526, I'd recommend that we consider this in the context of broader improvements to the interface reduction rules in MaterialX shader generation, rather than simply restoring a feature from 1.37.

Since these constant folding optimizations represent tradeoffs for the client, improving runtime performance but requiring additional shader recompilation when inputs are modified, it seems important to implement them with broad user controls over which categories of optimizations are applied to shader generation.

**Comment by jstone-lucasfilm** [comment]
Let's close out this issue along with #1526, in order to keep the focus on designing client-side controls for constant folding and reduced interfaces in shader generation.
