### ISSUE TITLE
Allow Material Editor to have Extensible Menu Items 

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1563]
## Issue

Instead of having to edit the source code for the Material Editor, it would be nice to be able to
extend it's functionality by adding in "custom" commands.

## Proposal

Allow for command line arguments to specify custom callbacks and creation of custom menu items.
This includes:
- Write only commands which can work on the current file by filename or by passing a string version of the document.
- Edit commands, which after execution on the current file reloads it back in.

**Comment by jstone-lucasfilm** [comment]
This is an intriguing idea, though I wonder whether it would ultimately be powerful enough to support the range of customizations that developers need in practice.  We may want to wait until a concrete use case requiring this approach materializes before moving ahead with a customization system.

For the specific use case of saving materials without UI position data, my sense is that the existing menu checkbox for this feature is a good fit, since it's such valuable functionality that all users should have access to it, without requiring them to go through a customization step.

**Comment by jstone-lucasfilm** [comment]
I'll close out this issue for now, and we can revisit this as we learn more about what types of customization are needed by the community.
