### ISSUE TITLE
SUG: Add limits to standard library nodes for UI

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1645]
## Suggestion

This is a general proposal that all inputs for definitions in the standard libraries (stdlib, pbrlib, bxdf, nprlib etc)
have at least min and max specified to allow UI to use these as range for input (`uimin` and `uimax`).
These could also be used for non-interactive validation purposes as well.

As a minimum bxdf (shading model) nodes should have proper ranges set.

### Issue

The current issue is that a guess must be made if you want to have things like UI sliders. There isn't really a good guess for all inputs as it is just a guess.

**Comment by erich666** [comment]
https://github.com/AcademySoftwareFoundation/MaterialX/pull/1646 adds two range limits for UsdPreviewSurface, and adds notes on how to rebuild in order to get changes to take effect (hopefully the makefile dependency will be fixed instead). These two simple fixes show what sort of file you need to modify and how to do it.

**Comment by jstone-lucasfilm** [comment]
Thanks to @kwokcb for this original suggestion and to @erich666 for the improvements to UsdPreviewSurface.

My sense is that we should take this work on a case-by-case basis, adding explicit limits for those controls that don't naturally fall within a 0-1 range.

I'll close out this suggestion for now, but feel free to add new tasks for specific node inputs that need additional work.
