### ISSUE TITLE
Versioning Numerics Of Some bxdf Nodes Incompatable With USD 23.08

### ISSUE THREAD

**Issue by SimonCSmith** [AcademySoftwareFoundation/MaterialX#1658]
After compiling and using MatrialX (1.38.7) with USD 23.08 I get "coding errors" output when it parses the following mtlx files due to the version of the nodes in the files being x.y.z rather than just x.y that the USD versioning parser seems to expect (which looks like it will then return the version of these nodes as 0.0).  I don't know which side this might be an issue on (if at all) but iI thought i'd report it.

ND_gltf_pbr_surfaceshader (gltf_pbr.mtlx):
Coding Error: in _ParseVersionString at line 70 ....\usd\ndr\declare.cpp -- Invalid version string '2.0.1'

ND_standard_surface_surfaceshader (standard_surface.mtlx):
Coding Error: in _ParseVersionString at line 70 ....\usd\ndr\declare.cpp -- Invalid version string '1.0.1'

ND_standard_surface_surfaceshader_100 (standard_surface.mtlx):
Coding Error: in _ParseVersionString at line 70 ....\usd\ndr\declare.cpp -- Invalid version string '1.0.0'

**Comment by meshula** [comment]
Could you report this on the OpenUSD repo as well please?

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @SimonCSmith, and that's a good suggestion, @meshula.

Since the authors of Autodesk Standard Surface used "1.0.0" and "1.0.1" as the version strings in their [original whitepaper](https://github.com/Autodesk/standard-surface/commit/352f7e9518f21a72358d6b90792635d60f8b7c6a), it seemed valuable to reflect those choices in MaterialX when implementing corresponding graphs.

Let us know if there are updates to MaterialX that would be valuable, though it may turn out that the right place to make this adjustment is on the OpenUSD side.

**Comment by SimonCSmith** [comment]
Thanks Nick/Jonathan for the quick response. I have reported it over on the OpenUSD side as requested - it does make the most sense all things considered.

**Comment by jstone-lucasfilm** [comment]
It looks like the discussion on the USD GitHub Issue is moving forward, so let's close out this original report, and we can focus on the discussion there.  Thanks again for bringing this to our attention, @SimonCSmith!
