### ISSUE TITLE
Graph Editor: Off-by-one error in visual updates

### ISSUE THREAD

**Issue by zicher3d** [AcademySoftwareFoundation/MaterialX#1782]
Please see videos below.
The attached test material should be copied into the libraries/stdlib folder. It will add a node called "test_update_38ten".

When connected to the output node, the materials correctly compiles and display, but changing any of the properties does not update.
This was working in 1.38.8.

[test_update_38ten.zip](https://github.com/AcademySoftwareFoundation/MaterialX/files/15044112/test_update_38ten.zip)

Behavior in 1.30.10:
https://github.com/AcademySoftwareFoundation/MaterialX/assets/7254958/de790e34-dbad-4554-9bb6-ecb4507df348

Behavior in 1.30.8:
https://github.com/AcademySoftwareFoundation/MaterialX/assets/7254958/144eb4f7-8faf-45ba-8b5d-9dafa12c52a9

**Comment by jstone-lucasfilm** [comment]
Good catch, @zicher3d, and I think this bug is a special case of an off-by-one error for visual updates in the Graph Editor.  At the moment, the user needs to first select _away_ from their newly-added node, and then select _back_ to it, after which the render view updates as expected.

This issue still occurs in MaterialX v1.39.2, and the built-in `disney_principled` node can be used in place of the provided custom node.

This seems like an important issue to fix in the Graph Editor, and I'm CC'ing @lfl-eholthouser and @kwokcb for their thoughts and advice.

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @zicher3d, and this should be resolved by #2150, which will be included in MaterialX v1.39.2.
