### ISSUE TITLE
Consider signing release artifacts

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/MaterialX#1999]
The OpenSSF Best Practices Badge suggests [signing release artifacts](https://www.bestpractices.dev/en/criteria),  using OpenEXR's [release-sign.yml](https://github.com/AcademySoftwareFoundation/openexr/blob/main/.github/workflows/release-sign.yml) workflow as a template. It's triggered on release creation and does these steps:
1. Runs `get archive` to generate a `<release>.tar.gz` artifact
2. Signs the `<release>.tar.gz` via [sigstore](https://www.sigstore.dev/) 
3. Uploads the resulting sigstore signature file along with the tarball. 

It looks like your release process already involves generating an explicit tarball, so your signing workflow won't need that step, but it will need to conform to you exact naming conventions.

**Comment by jstone-lucasfilm** [comment]
This has been implemented in #2009, and thanks to @cary-ilm for this suggestion!

**Comment by jstone-lucasfilm** [comment]
@cary-ilm I ran into those same issues, so I ended up taking a slightly different approach in signing release artifacts for MaterialX:

https://github.com/AcademySoftwareFoundation/MaterialX/pull/2009

The most notable difference is that we set `upload-signing-artifacts` instead of `release-signing-artifacts`, avoiding the creation of unnecessary build artifacts, and giving us more control over the timing of the final uploads to the release page.
