### ISSUE TITLE
Improve code validation framework

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#744]
This is a placeholder and the current additions under discussion include:

- Add in the ablity to install the MDL SDK and use mdlc for compile checks and/or dxr renderer for reference rendering
- Add in the ability to install reference osl and use oslc for compile checks and/or render for rendering (note that this is not reference rendering as yet, but will become more robust as osl implementations improve. ). This can leverage work done
for OCIO / OSL testing.
- Add in the ability to use glslangValidator to use custom uniform layouts. This allows to add Vulcan testing at least for syntax.
GPU support or software emulation for h/w is beyond the scope of this issue.

This is based on using a Python script to generate code (generateshader) and then a "validator" program as an input argument.

**Comment by jstone-lucasfilm** [comment]
Following up on this report in 2024, I believe the Vulkan validation step has been added to GitHub Actions, but there isn't yet a straightforward way to integrate OSL/MDL rendering into GitHub Actions, since we don't want to download prebuilt binaries in the cloud-based test suite for MaterialX.

I'll close out this original issue for now, but feel free to post new issues for proposals to better integrate OSL/MDL render tests in the future.
