### ISSUE TITLE
Updates to standard libraries for 1.39

### ISSUE THREAD

**Issue by numega** [AcademySoftwareFoundation/MaterialX#771]
The following changes should be made:
- ND_atan2_float's inputs should be renamed to iny and inx
- ND_normalmap should be renamed to ND_normalmap_float
- ND_normalmap_vector2 should be added
- ND_switch_* should have the in6-in10 inputs added
- ND_updirection_vector3 should be added
- ND_round_* should be added
- ND_safepower_* should be added
- ND_invert_* should be removed

**Comment by jstone-lucasfilm** [comment]
These are great catches, @numega, though we may want to apply these changes as part of the upgrade to MaterialX 1.39, rather than as fixes within 1.38.  This will allow us to use the document upgrade logic to maintain the look of 1.38 documents created with the current set of naming conventions (e.g. using "in1" and "in2" inputs for atan2).

**Comment by jstone-lucasfilm** [comment]
I've updated the title of this issue so that we don't forget these updates when implementing version 1.39.

**Comment by jstone-lucasfilm** [comment]
Updating this request from @numega in 2021, I should note that @ld-kerley has resolved nearly all of these issues in the current 1.38.9 and 1.39 builds (thanks Lee!).

The one remaining task is the addition of an `updirection` node, which is part of the MaterialX specification but is not yet supported in shader generation.
