### ISSUE TITLE
Sometimes maxTextureUnits is unintialized.

### ISSUE THREAD

**Issue by fire** [AcademySoftwareFoundation/MaterialX#881]
https://github.com/AcademySoftwareFoundation/MaterialX/blob/4f44b5a0e465ba6ec9abe8f246b504517fa32efa/source/MaterialXRenderGlsl/GLTextureHandler.cpp#L25-L27

Expected behaviour:

int maxTextureUnits is set to 16 and not uninitialized.

**Comment by jstone-lucasfilm** [comment]
@fire Can you elaborate on the situations in which maxTextureUnits would be uninitialized after the call to glGetIntegerv?  Is there a common error case that we're not handling?

**Comment by fire** [comment]
I'm not sure, but I think this happens when I'm on a server without a gpu. I may have removed some checks.

**Comment by jstone-lucasfilm** [comment]
@fire My current thinking is that this case should be caught during OpenGL initialization, so that we'd never reach this code path without access to a working OpenGL context (either using a GPU or virtual framebuffer).  That seems like a safer approach than omitting the initialization checks and trying to handle an invalid context within each individual call.

**Comment by jstone-lucasfilm** [comment]
I'll close out this issue for now, but feel free to open a new issue if you have proposals for related improvements in the future.
