### ISSUE TITLE
add combine9 and combine16 so we can create matrices

### ISSUE THREAD

**Issue by lucap-sidefx** [AcademySoftwareFoundation/MaterialX#912]
I think Rafal brought this up on the slack channel, but I wanted to put in here so it doesn't get forgotten. 

add comibine9 and combine16 so we can create custom matrices in our shaders.

**Comment by kwokcb** [comment]
`constant` (`matrix33` and `matrix44`) already exist so curious if those cannot be used ? 
e.g. They don't provide the ability to have upstream connections since there is only 1 input. In this case perhaps a variant on `constant` with 9 or 16 inputs to produce a `matrix33` or `matrix44` could be another option and might be clearer than a using a `combine` ?

Just some thoughts.

**Comment by dbsmythe** [comment]
In the WIP v1.39 Specification, there is a new proposed <creatematrix> node, that takes 3 vector3 or 4 vector4 row vectors, and creates a 3x3 or 4x4 matrix from them.  Those inputs could be connected to existing standard <combine3> or <combine4> nodes if you wanted to start with floats rather than row vectors.  Would this proposal address the request?

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @lucap-sidefx, and I believe this is now addressed with the merge of #1553.
