### ISSUE TITLE
variable R21 in mx_fresnel_airy (glsl) is unused.  bug?  

### ISSUE THREAD

**Issue by BrianSharpe** [AcademySoftwareFoundation/MaterialX#986]
There is a variable called R21 in mx_fresnel_airy() (libraries/pbrlib/genglsl/lib/mx_microfacet_specular.glsl, line 360) that is unused.
Is this a bug?
Or is it safe to simply comment it out?
cheers!

**Comment by jstone-lucasfilm** [comment]
Great catch, @BrianSharpe, and that same unused variable seems to be present in Laurent Belcour's original code.  The link has changed since @niklasharrysson developed the GLSL version for MaterialX, and can now be found here:

https://belcour.github.io/blog/research/publication/2017/05/01/brdf-thin-film.html

**Comment by jstone-lucasfilm** [comment]
@BrianSharpe If you have the bandwidth, feel free to remove this line from the GLSL code, and we should likely update the link to Laurent Belcour's paper to the new location above.

**Comment by BrianSharpe** [comment]
done  (https://github.com/AcademySoftwareFoundation/MaterialX/pull/989)
cheers!
